### ISSUE TITLE
Feat(search-input): optionsのインターフェースを変更する

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1008]
**機能追加理由・詳細**

- [x] search-input本体のpropsに、childrenが空っぽだったときに表示するメッセージを指定できるようにする（emptyMessage）
  - default: 選択肢がありません。
- [x] childrenを任意プロパティにする
- [x] childrenに空配列がセットされている場合、横に表示されるpopupにemptyMessageの中身を表示する
- [x] childrenがundefinedの場合、それ自体をセレクタにする

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
## filteredOptions のアルゴリズムの整理

この部分の実装の修正にあたり、実装が複雑でおかしいことになっているためここを分離して再度確認する

### 実装

```ts
const filterOptions =
  (match: (label: string) => boolean) =>
  (options: SearchInputOption[]): SearchInputOption[] =>
    options.flatMap((option) => {
      if (option.children.length === 0) {
        return match(option.label) ? [option] : [];
      }
      if (match(option.label)) return [option];
      const children = filterOptions(match)(option.children);
      if (children.length === 0) return [];
      return [
        {
          ...option,
          children: children,
        },
      ];
    });
```
