### ISSUE TITLE
Feat: 新規アイコン追加

### ISSUE THREAD

**Issue by junannko** [Wizleap-Inc/wiz-ui#1026]
**機能追加理由・詳細**
![スクリーンショット 2023-08-28 15 45 57](https://github.com/Wizleap-Inc/wiz-ui/assets/14048834/4e46a49c-2326-4bc4-bcc8-7010be8401d7)
- 新規アイコンの追加
- Icon/

**解決策の提案（任意）**

**その他考慮事項（任意）**
- アイコンのストロークの太さは今後400へ移行する予定
- 今後新規に作成したアイコンはfigma上、名前の頭に「wiz_400_」をつける

**Comment by ichi-h** [comment]
- 400系のアイコンは `WizI◯◯Bold` で命名を統一
- Filledのアイコンは `WizI◯◯Filled` で命名を統一
