### ISSUE TITLE
Feat: ボックス型のCheckboxを追加

### ISSUE THREAD

**Issue by junannko** [Wizleap-Inc/wiz-ui#1027]
**機能追加理由・詳細**

- checkedの塗りをfillとする
- Input/

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
![スクリーンショット 2023-09-07 19 35 32](https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/7ca3882e-f7fe-48b6-9504-abfa07916b94)

**Comment by ichi-h** [comment]
- 新しくcheckboxを作り直す
- 新しいバージョンを別コンポーネントとして作る
- 古い方をdeprecatedにする
