### ISSUE TITLE
Feat[SearchInput]:Tagバリエーションの追加 

### ISSUE THREAD

**Issue by kayokoito-dev** [Wizleap-Inc/wiz-ui#1034]
**機能追加理由・詳細**
<img width="450" alt="スクリーンショット 2023-09-01 14 55 48" src="https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/3796d198-1bc4-4529-8ef1-59162a5e120a">

- SearchInputにタグが入るバーションを追加したい
- リスト1行ごとにタグがある場合とない場合がある
- xs2のサイズのタグを使いたい

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
- タグのサイズは固定でよさそう
- ただ色違いパターンが今後入る可能性あり
- SearchInputOptionに `tag?: WizTagのpropsのinterface` みたいな形で持たせるのがよさそう
- wiz-tagのカラーバリエーションと、search-inputのタグのバリエーションが一緒になると良き
