### ISSUE TITLE
Bug(input系全般): 高さを44pxで統一したい

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1091]
**バグの説明**

おそらくborder込の高さで46pxになっているかも？
（time-pickerは44pxっぽい）

![スクリーンショット 2023-10-03 17 27 25](https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/1ad96b99-1633-444d-a5f5-d41a2cc26277)

checkbox-newやradio-newも考慮したい

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by RyushiAok** [comment]
縦44pxにチェック
- [x]  WizSearchInput 
- [ ]  WizSearchSelector
- [x]  WizTextButton
- [x] WizSelectBox
- [x] WizTimePicker
- [x] WizDatePicker
- [x] WizDateRangePicker
- [ ] WizCheckBoxNew (40px、Figma側は縦46px)
- [ ] WizRadioNew (40px, Figmaは46px)
- [x] WizPassword
- [x] WizText

**Comment by wmoai** [comment]
ここの `THEME.fontSize.xl2` を `xl3` にすればいいような気がするんですが、そういう話ではない感じでしょうか？

https://github.com/Wizleap-Inc/wiz-ui/blob/02879c3236f3c7b43327603ef5613b187f18e51d/packages/styles/bases/checkbox-new.css.ts#L41

**Comment by RyushiAok** [comment]
それで解決しました！失礼しました🙇‍♂️
