### ISSUE TITLE
Feat(input, dropdown): 入力中・選択中・選択肢の文字の色をgray.800に上げる

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1096]
**機能追加理由・詳細**

対象コンポーネント（figma要確認）

- base-inputとそこに依存しているコンポーネント（password-inputなど）
- dropdownに出てくる選択肢
- select-box
- search-selector
- date-picker
- date-range-picker
- time-picker
  - 選択肢と選択した文字の色両方
- search-input
  - 選択肢の文字の色

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
こちらですが、内容的に #986 と同じなのでこちらと同じ PR で対応する

**Comment by okakyo** [comment]
calendar, date-picker, date-range-picker は #986 にて対応中
