### ISSUE TITLE
Bug(popup): safariにて、dialog等のfixedで表示される要素上でpopupが出ているときにzoomすると、表示座標が狂う（？）

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1100]
**バグの説明**

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
## タスク内容
- [x] Safari にて、Input にフォーカスが当たると勝手にZoom される問題
  - fontSize を 16pxに変換する
  - viewport の設定にて、maximum-scale: 1.0 に変更する
→ **maximum-scale :1.0 に変更すること**で対応することに決定
- [ ] safariズーム時にposition: fixed上に表示されるpopupの座標が狂う問題
  - 現象として起きているのは dialog や Modal でpopup の上にpopup が表示される時に発生してる？
  - 今回はこちらの調査を行う

**Comment by okakyo** [comment]
## safariズーム時にposition: fixed上に表示されるpopupの座標が狂う問題の調査

**Comment by okakyo** [comment]
個人的な予測として、popup が、Input や Button の位置によってPopup が固定されないことが原因か...?
上記の類似したバグについて、以下の iPhone でポップアップが位置によって動作するバグが原因か？


https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/226efa70-966f-47d7-bb1b-00a4d425a9d5

**Comment by ichi-h** [comment]
文字が見えないから拡大縮小したのに、消えるという挙動は、ちょっと困る
（理想は根本解決だけど、取り急ぎの解決案としてはなくはない）

**Comment by ichi-h** [comment]
dialogやfullModalViewでbody要素にposition: fixedを付けたとしても、一番下よりもさらにスクロールをしたり、zoomをすることによって、背景がスクロールした判定になってしまい、popupの表示位置がずれる
