### ISSUE TITLE
Bug: React / WizDateRangePickerでエラーが出る

### ISSUE THREAD

**Issue by light-planck** [Wizleap-Inc/wiz-ui#1140]
**バグの説明**

React, WizDateRangePickerを利用するとconsoleに以下の警告が出る。

`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

**再現手順・画像・動画**

WizDateRangePickerを呼び出すと、上記のエラーがconsoleに出る。
なお、必須のpropsは渡している。

動作環境

```
"@wizleap-inc/wiz-ui-constants": "^0.14.0",
"@wizleap-inc/wiz-ui-react": "^0.40.0",
```

**期待される挙動・機能**

consoleに上記のエラーが出ない。

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
警告があるだけで、機能としては使えることを確認

**Comment by ichi-h** [comment]
> この対応でも警告は出なくはなりますが、警告が意味するところは、「ボタンの中にボタンを突っ込んだら意図したボタンを押せない可能性がある」ということだと思うので、本質的な問題解決にはならなさそうです……
> 
> ただ、これは実装が悪いという意味ではなく、そもそもデザイン的にボタンの中にボタンがある作りになっているので、そこから変える必要がありそう、という話になっております
> 
> 今回のこの警告でdate-range-picker自体が使えなくなるわけではないので、一旦警告はスルーしてしまって、デザインに関してはデザイナーさんの方にお時間あるときに案を出していただける事になったので、いったんそちらで進められればと思います……！

https://github.com/Wizleap-Inc/wiz-ui/pull/1156/files#r1423620424

**Comment by ichi-h** [comment]
警告は許容する方針になったのでcloseします！
