### ISSUE TITLE
Docs(icon): reactのIcon > Iconのstoryのアイコン名が正しく表示されない

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1178]
vue版のIcon > Iconのstoryは正しく表示されるが、reactは謎の文字列が表示されていてわかりにくい
reactの方もvueと同じようにアイコン名が表示されるようにしたい

vue
<img width="293" alt="スクリーンショット 2023-12-28 18 25 06" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/b6eaa7f0-34c2-4eda-9f03-2eb4c257dc16">

react
<img width="535" alt="スクリーンショット 2023-12-28 18 25 25" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/df0f7e7d-ba43-406b-a195-ea21ca8e64af">

**Comment by okakyo** [comment]
Google Chrome, Safari で確認したが、この現象を確認することができなませんでした。
画面幅や新しいバージョンに更新すると解決するかもしれません。

ご確認のほど、よろしくお願いします 🙇🏻 

### Google
https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/918a0b1c-d02a-4486-8be0-b9a8965af9a4


### Safari

https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/691bf6e8-d68a-4978-87f3-4d7a8de79b7f

**Comment by ichi-h** [comment]
なるほど、ローカルだと正しく表示されるのですね……！
正しく表示されないのはvercelのデプロイの環境の方で、ビルド時に何らかが起こっているんですかね……？

https://wiz-ui-react-wizleap.vercel.app/?path=/story/base-icon--icon
<img width="512" alt="スクリーンショット 2023-12-29 9 02 59" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/9ca7f8a2-8890-4408-8bbe-3195377b7be7">

**Comment by okakyo** [comment]
ChatGPT でこの原因を調査してもらったところ、以下の回答を得られました。

> Viteは、デフォルトでコードを最小化するため、`function.name`が省略されることがあります。これは、Viteが使用するTerserというJavaScriptコンパイラが、コードを最小化する際に関数名を省略するためです。
> 
> この問題を解決するには、Viteの設定を変更して、関数名が省略されないようにすることができます。具体的には、Viteの設定ファイル（`vite.config.js`）に以下のような設定を追加します。
> 
> ```javascript
> export default {
>   build: {
>     terserOptions: {
>       keep_fnames: true,
>     },
>   },
> }
> ```
> 
> この設定により、Terserは関数名を保持するようになります。
> 
> ただし、この設定はコードのサイズを大きくする可能性があるため、パフォーマンスに影響を与える可能性があります。そのため、この設定を使用するかどうかは、アプリケーションの要件とトレードオフを考慮して決定してください。
> 
> また、Storybookについては、Viteの設定が直接適用されないため、同様の設定をStorybookのWebpack設定に追加する必要があります。具体的には、`.storybook/main.js`に以下の設定を追加します。
> 
> ```javascript
> module.exports = {
>   webpackFinal: async (config) => {
>     config.optimization.minimizer[0].options.terserOptions.keep_fnames = true;
>     return config;
>   },
> };
> ```
> 
> これらの設定により、`function.name`が省略される問題を解決できるはずです。
>

**Comment by ichi-h** [comment]
@okakyo 

[chakra uiの方針](https://github.com/chakra-ui/chakra-ui/blob/7a06603bd61e06e0591bf68d6dd50daad2c336af/packages/components/src/icon/create-icon.tsx#L30-L48)を参考にしたのですが、画像のようにコンポーネントにdisplayNameプロパティを振った状態でビルドをすると、
<img width="983" alt="スクリーンショット 2024-01-24 10 20 52" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/d6bc49bb-be1d-4bfb-931a-a117fffcbd45">

ビルド後のファイルの中にそのプロパティと中身を保持できるので、これでterser問題は回避できそうです！
<img width="907" alt="スクリーンショット 2024-01-24 10 21 24" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/9a8f3dc2-89b6-4967-8c3d-6c427c704715">

なので、方針としては、

- packages/iconsにiconファイルを生成するスクリプトがあるので、そちらに `(ComponentName).displayName = (ComponentName)` の行を追加する
- story上で表示するコンポーネント名をnameからdisplayNameに変更する

これでうまくいくかを確認してみてほしいです！
