### ISSUE TITLE
Bug(dialog): (vue) ダイアログを閉じたときに、スクロール無効化が解除されない時がある

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1191]
**バグの説明**

**再現手順・画像・動画**

- ~~wiz-uiからダイアログを呼び出す~~
- ~~computedやwatchを用いて、ダイアログを閉じる動作に合わせて何らかの非同期処理を呼び出す処理を実装する~~
- ~~ダイアログが閉じてもスクロール無効化が解除されない~~

↓

上記の内容でwiz-uiでは再現ができませんでした
ただ、nextTickを使ってプロダクト側は回避できたことから、レンダリング周りのバグであることと予想

↓

ダイアログの表示・非表示の管理を変数をwatchし、その中の処理で実際のDOMを触ってスクロールの無効化の管理をしているため、vueのダイアログ周りのレンダリングと実際のDOMをいじる処理が競合してスクロール無効化が解除されなかった、という挙動に見える

↓

- 上記の内容を踏まえてwiz-uiでこのバグを再現する
- nextTickを使ってこのバグを解消できるかを調査
- 解消できた場合はその内容でPR、できなかった場合はそのとき考える

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
@okakyo 
こちらちょっと急ぎのタスクなので優先的にお願いいたします！ 🙇 
もしバグが再現ができそうになかったらご連絡いただけますと幸いです！

**Comment by okakyo** [comment]
Mac 環境下で確認したのですが、Safari, Chrome にて上記の事例は検証できなかったです。
一点気になったのが、ネスト状でダイアログを複数解除する途中でスクロールが有効化される事例がありました。
このバグについてこれに関連するのかを確認しておいた方がいいかもしれないです。

https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/8149befd-dfff-4ef7-a1b2-59c483ce80eb

**Comment by ichi-h** [comment]
@okakyo 
プロダクト側で起きていた問題はダイアログ1個で起きたので、ネストするところはまた別問題っぽいですね……
他の人でも再現できないところを見るに、ライブラリの問題というより、仮想DOMの仕組み上の問題の可能性があるので、

- 一旦このissueは保留
- プロダクト側はnextTickで対応してもらう

これで行こうと思います！
お手数おかけしてすみません！🙇 
調査してくださりありがとうございました！🙏
