### ISSUE TITLE
Bug(checkbox-new, search-input): チェックボックスの位置がズレている

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#1196]
**バグの説明**

search-inputのチェックボックスの位置が少しズレているところから判明しました

<img width="206" alt="スクリーンショット 2024-01-25 18 12 59" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/77895a64-4051-4eb7-86fe-d5267c67729c">

search-input以外にも、プロダクト側でもズレている説があるので、ご確認よろしくお願いいたします！

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
## 経緯

https://github.com/Wizleap-Inc/wiz-ui/issues/1139 の修正対応が原因のように思います。
- それまで、上下真ん中寄せで対応していたが、これを解除して margin, padding をそれぞれ充てることで対応していたため

だったと思います。
