### ISSUE TITLE
Bug: WizSearchSelectorの検索が直感的でない

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#1279]
**バグの説明**
SearchSelectorの検索が、適当な文字を入れても必ず何かしらが出てくるようになっていたり、大文字小文字などが多少狂うだけで全く別の結果で絞り込まれており、かなり使いづらく感じる

**再現手順・画像・動画**
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/43909370/caf64e27-f1a2-4d5c-87d4-3a30c23d17b5)
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/43909370/dea9042c-65b3-41d5-a93f-ca55172f9b89)
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/43909370/98edf2e1-6c4b-4148-a620-f502907b7f5c)

**期待される挙動・機能**
純粋に大文字小文字許容の文字列部分一致にしたら使いやすくなるように思います

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
Vue 側は 「レーベンシュタイン距離が最小なもの」 -> 「部分一致しているもの」 の順番で並んでいるのに対し、
React 側は元の順番のまま 「レーベンシュタイン距離が最小 or 部分一致」 フィルタがかかっていそう
