### ISSUE TITLE
Feat:(SearchSelector, react): 検索する文字列を外側から与えられるように

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#1281]
**機能追加理由・詳細**

Vue 側と同様、が外部から searchValue を制御できるようにしたいです！
（あるいは、addable セレクタでオプションを追加したときに検索文字列をリセットできると助かります）

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
- reactのみ！

- onCreateを実行した後に、searchTextの中身を空文字列にする
