### ISSUE TITLE
Bug(SearchSelector): Vue と React で並び順が異なる 

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#1282]
**バグの説明**

Vue 側は 「レーベンシュタイン距離が最小なもの」 -> 「部分一致しているもの」 の順番で並んでいるのに対し、
React 側は元の順番のまま 「レーベンシュタイン距離が最小 or 部分一致」 フィルタがかかっていそう

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
#1279 と重複のためcloseします！
