### ISSUE TITLE
Feat: (date-picker, date-range-picker, calendar):日付クリアボタン改修にともなうデザイン変更

### ISSUE THREAD

**Issue by junannko** [Wizleap-Inc/wiz-ui#1308]
**機能追加理由・詳細**

- 日付を選択したあとの日付クリアボタンが分かりづらい

**解決策の提案（任意）**

- 日付が入力されたらinput項目右端にクリアボタンを設置
- カレンダーアイコンをhoverするとクリアボタンが出る挙動を削除
- date-range-pickerは選択された日付が１つでもあればクリアボタンでリセットできる

**その他考慮事項（任意）**
ともない、下記デザインを修正

- 日付表記をyyyy年mm月dd日へ変更
- 選択日付のアクティブ状態を円形に変更
- date-range-pickerのinputのデフォルトwidthを広げる
- カレンダーの大きさをひとまわり大きくする

**Comment by ichi-h** [comment]
- 日付表記はユーザー側でformatができるようにする
  - defaultの表示はyyyy年mm月dd日
