### ISSUE TITLE
Bug(SearchInput, SearchSelector): 検索後の挙動が異なる

### ISSUE THREAD

**Issue by kawatakutaku** [Wizleap-Inc/wiz-ui#1334]
**バグの説明**

SearchSelector の方は 「文字列入力 -> 選択」 で文字列がリセットされるのに対し、SearchInput の方はリセットされない

**再現手順・画像・動画**

**期待される挙動・機能**

どちらかの挙動に合わせる

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
SearchSelector に統一
