### ISSUE TITLE
WizNotification: タブ名の文字数に余裕がほしい

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#190]
**機能追加理由・詳細**
6文字で改行されてしまうので某7文字が入りません
![image](https://user-images.githubusercontent.com/43909370/208235415-13fa9606-1eb3-4d20-84c9-61589be2b572.png)

**解決策の提案（任意）**
左右のpaddingを控えめにするか調整できるようにして入るようにしてほしいです

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
なんでこんなことしたんですかね...記憶にない（自分が作ったはずなのに）
修正します
