### ISSUE TITLE
WizNotification: メッセージ部分にURLなどの長い英字列があると三点リーダーが表示されずデザインが崩れる

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#191]
**バグの説明**
メッセージ部分にURLが入った際に範囲を超えても三点リーダーにならず▶︎を圧迫していた

**再現手順・画像・動画**
![image](https://user-images.githubusercontent.com/43909370/208235993-8ba6fb8d-3911-444f-b2f9-12d540ad7b0b.png)

**期待される挙動・機能**
break-allされている

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
ありがとうございます、修正します
