### ISSUE TITLE
WizNotification: NotificationItemのプロパティにurlが欲しい

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#192]
**機能追加理由・詳細**
クリック時に外部URLに飛ばしたい場合があり、APIから遷移先のURLも一緒に返したいため

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
パネルを押した時に遷移だけではなく既読更新処理などもするかなと思ったので、わざと遷移処理は組み込まず@clickからとってrouter.pushして使って欲しいという意図でした、これでは不都合でしょうか？ @Maple0922

**Comment by Maple0922** [comment]
あ、すみませんtypeの話でした！タイトル更新します
