### ISSUE TITLE
Feat: WizSelectBox: オプションの型をString以外で使いたい 

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#207]
**機能追加理由・詳細**
今SelectBoxのPropの型が
```
interface Props {
  options: Option[];
  value: string;
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  expand?: boolean;
}
```
となっているが，valueの型としてnumber型などでもできるようにしたい．

**解決策の提案（任意）**
コンポーネント間でジェネリクスのように型を指定できるといいと思ったのですが（`Props<T>`みたいな），無難に一般的な型に（もしかしたら`string | number`でも十分かもしれないです）に変更してもらえれば！（もし前者の方法ができるならご教授願いたいです笑）

 あと，もし意図的に`string`に縛っているなどの理由があれば，遠慮なくいってください！

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
html標準仕様でvalueがstringしか対応してないからが一番正しい回答だと思っています。
使う側の工夫次第でどうにでもできると思いますし、なるべく複雑な型設計にしたくないのでここは標準仕様に委ねたいです。

**Comment by mazyutyu** [comment]
なるほど，了解しました！

**Comment by sor4chi** [comment]
ちなみに先ほどConditionalにPropsの型を定義できない旨をお話ししましたが、Vueのバンドル後のDTSファイルをみてもらうとわかる通りVueではSFCからPropsをExtractionしてinterfaceの型をConstructorに変換するような仕様になっています。
そのため、型のConditionalができないというよりConstructorのConditionalができないが先ほどの正しい回答になるかと思っています。

**Comment by mazyutyu** [comment]
なるほど？propsのinterface->constructorの変換の際にconstructorの依存がconditionalに定義できないからpropsもconditionalに定義できない，ということであってますでしょうか？

**Comment by sor4chi** [comment]
大体あってます！複雑すぎるので興味あれば今度Vue SFCの型定義について語れます

**Comment by mazyutyu** [comment]
型定義は自分も論理学とのつながりで考えてる部分ではあったので興味ありますｗ
お時間あるときに聞いてみたいですね

**Comment by sor4chi** [comment]
対応予定はありませんが、今後設計方針変更の過程で対応できるようになるかもしれません
