### ISSUE TITLE
Bug: WizIHintがexportされていないようです。

### ISSUE THREAD

**Issue by nagaihiroki-git** [Wizleap-Inc/wiz-ui#234]
**バグの説明**
wiz-uiのバージョンを0.3.4から0.4にあげたところ、WizIHintがimportできなくなってしまいました。
**再現手順・画像・動画**
![2023-01-07 18 22 28 localhost cce912056994](https://user-images.githubusercontent.com/82458324/211143526-80694bba-39fd-4eb8-95a5-7a5c25b3a335.png)

**期待される挙動・機能**
importできるようにしてほしいです！

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
v0.4.0でWizIHintはWizIHelpに統合されました
