### ISSUE TITLE
Feat: Iconの追加(リロード、チェック、イタリック体のi)

### ISSUE THREAD

**Issue by kentyisapen** [Wizleap-Inc/wiz-ui#241]
**機能追加理由・詳細**
下記3つのアイコンの追加をお願いいたします！
![image](https://user-images.githubusercontent.com/83551863/211227108-5d115072-96ce-481d-907f-e582e7ca9be7.png)
![image](https://user-images.githubusercontent.com/83551863/211227109-f002bfec-bb7e-4880-b1d4-3d45be0110e1.png)
![image](https://user-images.githubusercontent.com/83551863/211227111-4bfbe1bf-4c7b-4789-9428-27b20d439e31.png)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
ありがとうございます、対応します
