### ISSUE TITLE
Bug: WizBadgeで下層のButtonのClickイベントが発火しない

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#248]
**バグの説明**

図のように，WizIButton に WizBadge を適用しているとき，WizBadge にマスクされている部分で WizIButton のクリック判定がなくなってしまい，押しにくくなる．

**再現手順・画像・動画**

<img width="43" alt="スクリーンショット_20230110_173658" src="https://user-images.githubusercontent.com/114043156/211501623-bf5a1f97-1a5c-46f6-887e-3be85ebeb0b4.png">

**期待される挙動・機能**

マスクされている部分でも click イベントが発火するようにする，あるいは Badge 含めた部分に click の範囲を拡張する．

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
WizBadgeにonClickつけますね
