### ISSUE TITLE
Bug: Stackにてgxとgyの両方を指定するとgxが効かなくなる

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#253]
**バグの説明**

Stackにてgxとgyの両方を指定するとgxが効かなくなります

**再現手順・画像・動画**

- storybookでStack > Defaultを選択し、箱の数を10個ほどに増やす
- gxとgyの両方を指定するとgxのスタイル  `gap: 0 XXrem;` が打ち消され、`gap: XXrem 0;` で上書きされてしまう

![スクリーンショット 2023-01-11 11 51 57](https://user-images.githubusercontent.com/85932406/211707422-edc5259a-4d97-4688-b491-2a8d2fc77736.png)

**期待される挙動・機能**

- gxとgyの両方を指定できるようになる

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
OH... 気づかなかった... ありがとうございます。
もし至急でしたら今日出勤できなそうなので他の方にPRお願いする形になります。
@ichi-h

**Comment by ichi-h** [comment]
至急ではないですね!
可能であれば月曜の朝までに治っていれば嬉しいという感じです!

**Comment by sor4chi** [comment]
rowGap/ColmunGapで対応可

**Comment by sor4chi** [comment]
gapXStyleとgapYStyleをrowGapとcolmunGapでの実装に変える
