### ISSUE TITLE
Bug: WizTooltipの横幅が広い

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#255]
**バグの説明**
横幅が見た目以上に広いため、親要素の外にはみ出してしまう

**再現手順・画像・動画**
![image](https://user-images.githubusercontent.com/43909370/211783219-dacafb63-0a01-449c-ba6f-8633bf38e10d.png)

**期待される挙動・機能**
見た目通りの広さである

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
@Maple0922 
これなんか問題あるんですか？

**Comment by Maple0922** [comment]
テーブルの端っこに置いてるとテーブルの横幅以上に突出して、そこまでスクロールできるようになっちゃいます
