### ISSUE TITLE
Feat: WizSelectBoxで文字が長かったときは改行ではなく3点リーダーが表示されてほしい

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#256]
**機能追加理由・詳細**
伊藤さんに確認をとったため
![image](https://user-images.githubusercontent.com/43909370/211789687-9637d734-d1df-4b96-90f7-e8546a9b5efd.png)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
確認撮っていただいてありがとうございます、
こちらも安心して修正できます！

**Comment by sor4chi** [comment]
Optionの右側に数字出せるようにしたい
