### ISSUE TITLE
Bug: Safariでapiを読み込んだ後に背景の色が消える

### ISSUE THREAD

**Issue by HMomoki** [Wizleap-Inc/wiz-ui#258]
**バグの説明**

**再現手順・画像・動画**
顧客管理または案件配信画面をSafariでひらけば再現できる

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
要再現

**Comment by HMomoki** [comment]
![スクリーンショット 2023-01-12 17 39 08](https://user-images.githubusercontent.com/77085014/212018435-315a29d8-0bce-4ea3-a9b2-02f1bc02ba25.png)

**Comment by HMomoki** [comment]
![Uploading スクリーンショット 2023-01-12 17.39.58.png…]()
![スクリーンショット 2023-01-12 17 40 22](https://user-images.githubusercontent.com/77085014/212018665-bb76d297-7e8e-4db9-961e-11ac56e019f2.png)
![Uploading スクリーンショット 2023-01-12 17.40.14.png…]()

**Comment by sor4chi** [comment]
あっメモ勝手にコメントされてました、すいませんありがとうございます。
背景はWizUIが持っていない部分なのですがなんで消えるんですかね...
