### ISSUE TITLE
Feat: WizBoxにmin/max

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#259]
**機能追加理由・詳細**
WizVStackの中でWizSelectBoxを使う時に横方向ははみ出したらscroll、縦方向のセレクトボックスのアイテムは表示させたいため
![image](https://user-images.githubusercontent.com/43909370/211891335-724563ec-f44b-4f0c-ac1c-a189804f3148.png)
![image](https://user-images.githubusercontent.com/43909370/211891497-fb13e9d0-342e-49a4-9c49-5a31167eeb77.png)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
<WizBox overflowY="scroll">
  <WizStack /> 
</WizBox> 
出できませんか？

**Comment by Maple0922** [comment]
そもそも個別設定しても出てくるか怪しく、、
お手隙の際にみてもらえると助かります🙇‍♂️

**Comment by sor4chi** [comment]
これ片方(-yや-x)だけhiddenにしても僕環境だと動かなかったんですけどどうですかね

**Comment by sor4chi** [comment]
WizBoxにminWIdth/minHeight/maxWidth/maxHeightをpropsとして持たせて設定できるようにする(string)
