### ISSUE TITLE
Feat: WizTabの文字がはみ出した時に改行ではなく3点リーダーにしたい

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#261]
**機能追加理由・詳細**
改行されると他の改行されてないタブが浮き上がってしまうため
<img width="422" alt="image" src="https://user-images.githubusercontent.com/43909370/211962082-25787935-4340-4dc6-8852-81db3ca0a07e.png">

**解決策の提案（任意）**
-webkit-line-clamp

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
そんな長い文字入ることあるんですか？そしたらwidth指定できた方がいい気がする

**Comment by sor4chi** [comment]
@Maple0922 
そもそもタブのメッセージが一部隠れること自体だめだと思うんですがそういう場合がありそうなんですか？

**Comment by Maple0922** [comment]
長い文言がなくなったので一旦closeしました
