### ISSUE TITLE
Feat: WizCardのmainHeaderAreaがsubHeaderAreaと併用しないと表示されない

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#262]
**機能追加理由・詳細**
mainHeaderAreaだけ使いたい時があるので単体でも表示されるようにしてほしい(仕様？バグ？)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
これはバグっぽいですね、みます
