### ISSUE TITLE
Feat: WizTagでwidthを指定できるようにしてほしい・Icon追加

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#264]
**機能追加理由・詳細**
横幅統一のタグを実装する要件があるため
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
stringでwidth指定、textalign center

**Comment by sor4chi** [comment]
Variant3つに絞って色変更不可に
iconをつけれるようにする
