### ISSUE TITLE
Bug: WizProgressBarの丸がWizNotificationを超える

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#285]
**バグの説明**
WizNotificationとWizProgressBarが被った時、WizProgressBarの丸がNotificationより上にきてしまう

**再現手順・画像・動画**
<img width="363" alt="image" src="https://user-images.githubusercontent.com/43909370/212479893-c2c3abd7-a140-4bc5-aa97-2aff56d60882.png">

**期待される挙動・機能**
WizNotificationの方が上に表示される

**その他考慮事項（任意）**

**Comment by Maple0922** [comment]
WizNotificationとWizProgressBarの書く順番を変えて親のStackにreverseかけたら一旦解決したので、こちらの優先度は低くて大丈夫です

**Comment by sor4chi** [comment]
これの原因が特定できないんですけど、STGで実際に見れますか？

**Comment by sor4chi** [comment]
azms!

**Comment by sor4chi** [comment]
![ScreenCapture 2023-01-15 1 11 53](https://user-images.githubusercontent.com/80559385/212482341-f7843909-dde0-4b41-b34e-7f2baa81ec04.png)
ここのz-indexを2以降にしたら解決したんですけどここって外部から当ててる場所ですか？

**Comment by Maple0922** [comment]
この辺りのページでz-index当ててる箇所はありませんでした

**Comment by sor4chi** [comment]
えまじですか！？

**Comment by sor4chi** [comment]
https://user-images.githubusercontent.com/80559385/212483851-59c13418-3d22-4f47-9256-91d8232fdc80.mov

じゃあこれなんだ...

**Comment by Maple0922** [comment]
`packages/wiz-ui-next/src/components/base/header/header.vue`
これの `headerZIndex`がつけてるみたいです！

**Comment by sor4chi** [comment]
あーーーーーーなるほど
