### ISSUE TITLE
Feat: WizIconの追加(upload)

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#286]
**機能追加理由・詳細**
アップロードボタンのアイコンが必要なため

**解決策の提案（任意）**
![upload](https://user-images.githubusercontent.com/43909370/212483281-d9ff5522-231c-40c1-a78c-6b83fcb461f7.png)

**その他考慮事項（任意）**
上記Figmaからexportしました、よろしくお願いします＠

**Comment by sor4chi** [comment]
AZMS
