### ISSUE TITLE
Feat(Upload): デザイン改修

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#296]
**機能追加理由・詳細**

- D&Dとプログレスとアップロードされたファイルの3つが同時に表示されている
  - アップロード → プログレス → アップロードの順にコンポーネントの表示が切り替わる

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
これ結局Figmaの要件変わらない限りかいはつできなくないですか？
