### ISSUE TITLE
Feat(Tooltip): 出現方向を指定できるようにする

### ISSUE THREAD

**Issue by tabata-itsuki** [Wizleap-Inc/wiz-ui#299]
**バグの説明**
Tooltipを上の方に置くとHeaderの下に潜ってしまいます。
**再現手順・画像・動画**
https://wizleap.slack.com/archives/C03UB1CL2LS/p1673230487098089?thread_ts=1673229595.385929&cid=C03UB1CL2LS
**期待される挙動・機能**
tooltipの表示方向を制御できるようになるか、もしくはHeaderの下には潜らないようになってほしいです！

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
ありがとうございます！対応しておきます
