### ISSUE TITLE
Feat(Upload): アップロード後のレスポンスを受け取れるハンドラを受け付けられるようにしたい

### ISSUE THREAD

**Issue by sor4chi** [Wizleap-Inc/wiz-ui#319]
**機能追加理由・詳細**

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
@nagaihiroki-git 
お願いできますでしょうか？

**Comment by nagaihiroki-git** [comment]
@sor4chi 
承知いたしました！

**Comment by ichi-h** [comment]
- D&Dとプログレスとアップロードされたファイルの3つが同時に表示されている
  - アップロード → プログレス → アップロードの順にコンポーネントの表示が切り替わる
