### ISSUE TITLE
Feat(WizChatCard) 既読の文字にtooltipをつけたい

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#327]
**機能追加理由・詳細**
読者を表示できるようにしたいため

**解決策の提案（任意）**
popupContent: string 
もしくは
readers: string[]  (汎用性があまりにも低い？)

white-space: pre-wrapをつける
**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
#326 のreadCountはreaders.lengthから取れるのでreadersで実装するのが良さそう
