### ISSUE TITLE
Feat: (WizText) text-align プロパティが欲しい

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#353]
**機能追加理由・詳細**
複数行にわたる文章で，事前に分かっている文章であれば Stack + text で左揃えなどは実現できるのですが，
whiteSpace などで複数行にまたがる場合，左揃えなどが実現できないので text-align プロパティで左揃えなどが指定できると嬉しいです．
text-align プロパティを追加したくない，すでに似た機能を実現できる等あれば遠慮なくいってもらえると！

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
textAlign propsの追加、型は`"start" | "end"| ...`
