### ISSUE TITLE
Bug(WizTooltip): maxLinesを指定したWizTextにWizTooltipをかけるとWizTextの横幅が広がる

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#354]
**バグの説明**
https://github.com/Wizleap-Inc/wiz-ui/pull/332/files#diff-02371f9055ca8b2a6fea373ae311aba4d9fb77242e67ef8f661571b1b4f4110cR5
おそらくWizTooltipにwidth: max-contentをかけている影響で、中のWizTextがつられて長さ分まで広がってしまい、line-clampが効かなくなっている感じかと思います

**再現手順・画像・動画**
<img width="369" alt="image" src="https://user-images.githubusercontent.com/43909370/217177615-e7ccc7b0-585a-4ef1-8224-aee89cabf9f7.png">

max-contentあり
<img width="369" alt="image" src="https://user-images.githubusercontent.com/43909370/217178207-371aae2c-93f8-4b22-adb6-ad3e440b2d2b.png">

max-contentなし
<img width="369" alt="image" src="https://user-images.githubusercontent.com/43909370/217178439-cb0cbe68-6019-4793-9dca-9717a4fa6ca9.png">

**期待される挙動・機能**
画像3枚目のような形になっている

**その他考慮事項（任意）**
```vue
<WizTooltip>
  <template #content>
    長い文章長い文章長い文章長い文章長い文章長い文章
  </template>
  <WizText :maxLines="1" fontSize="sm">
    長い文章長い文章長い文章長い文章長い文章長い文章
  </WizText>
</WizTooltip>
```

**Comment by Maple0922** [comment]
https://github.com/Wizleap-Inc/wiz-ui/pull/355
原因と思われる部分を消しただけですが、治りそうで他に問題なさそうであればマージお願いします

**Comment by sor4chi** [comment]
問題あったので対応します
