### ISSUE TITLE
Feat(WizNavItem): ホバーすると詳細選択ができる機能が欲しい

### ISSUE THREAD

**Issue by YamatoKato** [Wizleap-Inc/wiz-ui#356]
**機能追加理由・詳細**
ホバー時に右横にアイテムを一覧表示させたい。
slackにて詳細説明
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
これは要検討

**Comment by sor4chi** [comment]
左側のNavItemをHoverした時は右側のPopupはHoverしてる時だけ表示
左側のNavItemをClick(Activate)した時は右側のPopupは他がClickされるまでずっと表示

![Image](https://user-images.githubusercontent.com/80559385/222648040-433ee818-9a2a-4053-8ee6-a3ab72ce92b6.png)

**Comment by sor4chi** [comment]
depends on #428
