### ISSUE TITLE
Feat: 色がつけられたり、文字の場所を割と自由に設定できる出来る表がほしいです。！

### ISSUE THREAD

**Issue by nagaihiroki-git** [Wizleap-Inc/wiz-ui#359]
**機能追加理由・詳細**
下記のようなフォームの実装がしたいのですが、現状のコンポーネントだけだと難しいので、新しいコンポーネントを作っていただきたいです！（方針だけ教えていただければ、作成いたします！）
https://www.figma.com/file/FpwRf6yyPltG0vX95XKJo9/%E3%83%9E%E3%82%A4%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC?node-id=339%3A37483&t=ZESlcRg8f09gtLNa-0
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
@nagaihiroki-git 解決したのであればcloseしたいのですがどうですか？
