### ISSUE TITLE
Feat: (toggle button) アクティブかどうかをv-modelで制御したい

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#363]
**機能追加理由・詳細**
toggle button のクリック時にアクティブか非アクティブかでアクションを変えたい場合，toggle button の状態が知りたい，toggle button の最初の状態をアクティブにしたい等.
外からbooleanの変数によってv-modelでアクティブかどうかを制御できるようにしたい．

**解決策の提案（任意）**
現在，isActive の変数として内部で管理しているものを modelValue として外側で管理するようにすることは可能でしょうか．(破壊的変更になりそうなので，早めに対応してもらえると幸いです)

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
これはそうですね...作った方に連絡してみます

**Comment by sor4chi** [comment]
custom componentへのv-model定義をしてください。
参考: https://ja.vuejs.org/guide/components/v-model.html
