### ISSUE TITLE
Feat(WizButton, WizTinyButton): widthを指定できるようにしてほしい

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#380]
**機能追加理由・詳細**
UIの中で、幅を調整したい場面があるため
今の時点ではWizTinyButtonのみ必要です！

**解決策の提案（任意）**
widthプロパティを生やす

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
#398 で対応します！
