### ISSUE TITLE
Feat: WizBoxでbackdrop-filter: blur を指定できるようにしたい

### ISSUE THREAD

**Issue by tabata-itsuki** [Wizleap-Inc/wiz-ui#385]
**機能追加理由・詳細**
モザイクみたいなUIを被せたいため。
https://wizleap.slack.com/files/U01GYMNQ4E4/F04QPE3KL9X/____________________________2023-02-20_6.34.36.png
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
WizBoxにbackdrop blur要素を追加するだけで実現できそうです @ichi-h
