### ISSUE TITLE
Feat(WizNavItem): disabled属性をつけたいのと、hoverしたらtooltipが表示できるようにしたい

### ISSUE THREAD

**Issue by tabata-itsuki** [Wizleap-Inc/wiz-ui#411]
**機能追加理由・詳細**
https://wizleap.slack.com/files/U01GYMNQ4E4/F04R5SP1H8W/____________________________2023-02-27_14.47.29.png
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
![Image](https://user-images.githubusercontent.com/80559385/222649731-3d8eef52-9855-4bc5-b33b-c97294e06706.png)
