### ISSUE TITLE
Feat(search-selector): 検索精度の向上

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#433]
**機能追加理由・詳細**

例えば「20」と検索したときに、トップに「test20」がこないのはあまり直感的ではない

![スクリーンショット 2023-03-06 17 00 45](https://user-images.githubusercontent.com/85932406/223051597-69a45d98-1f33-4f63-b44f-cb951f02dd4f.png)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
アルゴリズムを確認したのですが、候補の表示における計算について、`20` を入力した際、
`test10` と `test20` でのコストに差がないことが原因のようです。

アルゴリズムの実装がどこか間違ってるかもしれないです。

![スクリーンショット 2023-03-10 1 47 12](https://user-images.githubusercontent.com/29594820/224094604-4ea44016-3d65-49d5-9fd7-2ea9e67c34b6.png)
