### ISSUE TITLE
Feat: (Table系) table-layout プロパティが欲しい

### ISSUE THREAD

**Issue by mazyutyu** [Wizleap-Inc/wiz-ui#440]
**機能追加理由・詳細**

Widthなどを細かく指定したいとき，table-layoutをfixedにしないとuiが崩れてしまうことがあるため，table系のコンポーネントにtable-layoutプロパティが欲しいです

**解決策の提案（任意）**

**その他考慮事項（任意）**

一応既存でも似たuiを作ることはできるため，優先度は下げてもらって大丈夫です．

**Comment by sor4chi** [comment]
table-layout (optional boolean)の拡張

**Comment by okakyo** [comment]
確認ですが、 table-layout の型は Boolean でよろしいでしょうか。
個人的には table-layout の props (auto, fix etc...) が入力されるようにしてもいいと思うのですが、どうでしょうか。

**Comment by mazyutyu** [comment]
私も auto, fix などのリテラルで指定するイメージで issue 投げました．

ただ，プロパティとして指定するのが fix と auto の二種類程度しかないのであれば `fixed: boolean` などのプロパティで fixed か auto かを指定するように指定していただいても大丈夫です，そこら辺はやりやすい方でお願いします
