### ISSUE TITLE
Bug: WizSearchSelector：長い文言でセレクターが見切れる

### ISSUE THREAD

**Issue by YamatoKato** [Wizleap-Inc/wiz-ui#442]
**バグの説明**
選択肢として出てくる文言に長い文字列がある場合、セレクト欄が見切れてしまう。

**再現手順・画像・動画**
![image](https://user-images.githubusercontent.com/95395675/223926887-977c29a5-6d5d-420f-9aca-9773cf382a88.png)

**期待される挙動・機能**
![image](https://user-images.githubusercontent.com/95395675/223927287-fe786f79-23da-43cc-a36d-fd1e445efe01.png)
このように右側にセレクターの表示が延長する

**その他考慮事項（任意）**
現在2023/03/09、フロント側の実装で、21文字以上の文字列がoprionsのlabelに入る場合は、21以降の文字列を排除して、3点リーダーを付与して対応中。
![image](https://user-images.githubusercontent.com/95395675/223943127-25f848eb-c35a-43a0-b3e1-da0e1d1c6961.png)

**Comment by ichi-h** [comment]
@YamatoKato 
これ出てきたpopupの折り返し効いていますか？
（一番最初の画像は効いていなさそうだったので）

**Comment by sor4chi** [comment]
文字列で最大長指定ができないので、maxWidth240px(15rem)以上でoverflowにしてください。

**Comment by YamatoKato** [comment]
@ichi-h 折り返しは効いていないようです。
