### ISSUE TITLE
Feat(select-box, search-selector, A11Y): セレクターをキーボードで操作できるようにする

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#445]
**機能追加理由・詳細**

- 矢印キーでoptionの選択ができる
- enter keyでoptionの選択ができる
- tabindexが使える

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
option の選択で、矢印キーで選択できるようにするということでしたが、以下のような仕様でよろしいでしょうか。

https://user-images.githubusercontent.com/29594820/227718088-173e18e5-2724-48be-98f8-97e3e26d9cb9.mov

**Comment by ichi-h** [comment]
まさに動画みたいな感じです！
とりあえずの目指したいところは、

- dropdownが出た時に矢印で選択肢が移動できる
- enterでoptionが選択できる
- tabindexが効く
- select-boxにフォーカスが当たっている状態でenterを押すとdropdownが開く

あたりができればな考えています！

ただ、めちゃくちゃ理想的には、HTMLのセレクターと同様のレベルでショートカットができることではありますね！
https://developer.mozilla.org/ja/docs/Web/HTML/Element/select
