### ISSUE TITLE
Refactor: vanilla extractのimportをnamed importではなく import * as styles from "..."に全て置き換えたい

### ISSUE THREAD

**Issue by sor4chi** [Wizleap-Inc/wiz-ui#456]
**機能追加理由・詳細**

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
こんな感じで置き換えしてほしいです。
ただ単に綺麗にしたいだけですが...

![ScreenCapture 2023-03-24 15 31 16](https://user-images.githubusercontent.com/80559385/227443168-ca887d9c-48cf-487e-b376-06799e415e46.png)
![ScreenCapture 2023-03-24 15 30 57](https://user-images.githubusercontent.com/80559385/227443160-5875a6d5-34f0-400e-b422-f3e00a920c57.png)

**Comment by okakyo** [comment]
[ASK ] 
こちらについて2つほど確認したいのですが、

こちらの呼び出し方は 

```typescript
import * as styles from "---.css"

const {
  // 必要なcss
}　= style

----------

import * as styles from "---.css"

<div class= [styles.Styles]>
</div>
```
と呼び出すようにしたほうがいいでしょうか。また、

呼び出している Style の数が 3 つ以下である場合はそのままで、4個以上呼び出しているものだけを変更するようにしてもいいかなと思いますが、どうでしょうか。

**Comment by okakyo** [comment]
- [ ] a~b
- [ ] c~d
- [ ] e~g

**Comment by ichi-h** [comment]
全PRマージしました！
ありがとうございました :bow:
