### ISSUE TITLE
Feat(table): colspan, rowspan (セル結合) の対応

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#506]
**機能追加理由・詳細**
WizCardTableをパクるだけですね

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
3 点確認ですが 、
- 現在、th にのみ `colSpan` だけが適用されているのですが、`rowSpan` も追加した方がいいですか。 
- th だけでなく、td にも `colSpan`, `rowSpan` にも適用した方がいいですか。
- rowSpan があるとどのように結合されるかのデザイン例があれば教えてください。

以上の点でご確認のほどよろしくお願いします。

**Comment by okakyo** [comment]
WizCardTable ですが、 rowSpan はデザインや仕様的に難しいかもしれないです。
機能として付与したいと思うのですが、ここではあまり推奨しない方がいいかもしれないです。


![スクリーンショット 2023-04-06 22 56 44](https://user-images.githubusercontent.com/29594820/230400162-2c7cd11b-f4c3-412f-a03e-6a8440db92fd.png)

**Comment by sor4chi** [comment]
@okakyo このissueはWizCardTable以外に対しての拡張issueです、説明足らずで申し訳ないです
