### ISSUE TITLE
Feat(popup): 回り込みロジックを使うか使わないかを選択できるようにする

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#605]
**機能追加理由・詳細**

例えばブラウザを拡大表示すると、popupが表示領域よりも大きくなることがあり、その場合画面外にpopupが回り込んでしまうことがあるため、その解決策として、回り込みを意図的に発火させないようなプロパティをpopupに設けたい

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by sor4chi** [comment]
#512 も
