### ISSUE TITLE
Bug(popup): safariにてpopupを閉じると中身だけが非表示になるがカードが消えない

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#615]
**バグの説明**

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
影が残る原因についての対策案：

- https://hapicode.com/css/safari-tap-shadow.html#%E5%90%84%E3%83%95%E3%82%99%E3%83%A9%E3%82%A6%E3%82%B5%E3%82%99%E3%83%BC%E3%81%AE%E3%83%86%E3%82%99%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-css

これで修正できるかを検証する
