### ISSUE TITLE
Bug(search): safariにてチェックボックスのスタイルが崩れる

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#616]
**バグの説明**

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
### 検証：

親、子コンポーネント はスタイルが崩れていないものの、
孫コンポーネントではスタイルが崩れてしまっている

![スクリーンショット 2023-04-22 15 41 24](https://user-images.githubusercontent.com/29594820/233767517-6ce8f11a-e05c-4686-a365-f0c445f8e688.png)

![スクリーンショット 2023-04-22 15 36 30](https://user-images.githubusercontent.com/29594820/233767278-049a0335-87c2-4586-97a7-797f85f8edb4.png)
