### ISSUE TITLE
Feat: WizTagのvariantに黄色を追加していただきたいです！

### ISSUE THREAD

**Issue by nagaihiroki-git** [Wizleap-Inc/wiz-ui#691]
**機能追加理由・詳細**
新規機能の開発で使用するので、お願いいたします！
https://www.notion.so/wizleap/2023_4_11_-c51c986d831a4cc1b034b621a8c7f004?pvs=4#5a773433f2794eed89aae68c2c1f2ff6
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
# 新規追加

- variant名: yellow
  - 背景色: yellow.300
  - 文字色: yellow.800
  - アイコン色: yellow.800
- variant名: blue
  - 背景色: blue.300
  - 文字色: blue.800
  - アイコン色: blue.800

# 変更

- variant名: error → **red**
  - 背景色: red.300
  - 文字色: red.800
  - アイコン色: red.800
- variant名: success → **green**
  - 背景色: green.300
  - 文字色: green.800
  - アイコン色: green.800
