### ISSUE TITLE
Bug(WizMeterGraph): グラフ下部に余白がある

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#701]
**バグの説明**

MeterGraphを使ったとき，ui上で2.5remの余白がある（コンポーネント上でその部分は使われていない気がしたので，なくしてもいい気がしました）

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
## 仕様の確認

このケースについて、どちらの方式で進めた方がいいかについて確認してもらいたいです。

円の中心を下にずらす|height を 35 にする
---|---
![スクリーンショット 2023-05-11 22 50 30](https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/01511b69-7daa-4de1-8e83-0cbe69fc7847)|![スクリーンショット 2023-05-11 23 03 34](https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/47e69de0-c30e-4d35-8a40-716f8011585d)
