### ISSUE TITLE
Feat(NotificationPanel): デザイン変更

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#716]
**機能追加理由・詳細**

主な変更点
• SPデザインを追加（Width可変）
• Default時、「＞」アイコンをGreen 800に
• PCのみHover時、背景色をGray 200に
• Press時、全体的にOpacityをかけるのをやめて、背景色をGreen 300に

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by kayokoito-dev** [comment]
![Notification_list_chat](https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/1ee20c7f-c0d9-48b9-a031-8720ce0742b9)
![Notification panel](https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/e97ec5b0-b591-426b-902c-87310d15e5bf)
