### ISSUE TITLE
Feat(InputText): padding変更

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#719]
**機能追加理由・詳細**

主な変更点
・padding-left&right: 8px; にする

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by kayokoito-dev** [comment]
![Property 1=default](https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/bd86783d-56f3-4bc3-a299-d94741cb1f46)
