### ISSUE TITLE
Feat(ShowMoreLess): SPサイズの追加とPCHover＆Press時の色変更

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#725]
**機能追加理由・詳細**

主な変更点

PC変更
・Hover&Press： Background: Gray 200, Text&icon color: Green 800;

スマホ追加
・サイズ：高さ44px
・Defaultのみ：Background: Gray 200, Text&icon color: Green 800;

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by kayokoito-dev** [comment]
![ShowMoreLess](https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/ae68df23-ac7e-43be-9e4d-bdb07d3adab3)

**Comment by ichi-h** [comment]
@kayokoito-dev 
高さモバイルのときだけ44pxとのことですが、PCは狭いままにしますか？？
（どちらも44pxでも良いのではないか、という意見が上がっておりまして）
