### ISSUE TITLE
Feat: Form Groupか、Form Control にdirectionを追加していただきたいです！

### ISSUE THREAD

**Issue by nagaihiroki-git** [Wizleap-Inc/wiz-ui#729]
**機能追加理由・詳細**
https://wizleap.slack.com/files/U02UZS2MCB1/F057QH7K7BQ/image.png
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
おそらくwiz-uiでコンポーネントを提供しなくとも実装できる内容だと思うので、いったんproduct側で実装してください！
今後、こういったUIが頻繁に用いられるようでしたら導入を検討いたします！

**Comment by ichi-h** [comment]
@kayokoito-dev 
こちらいかがでしょうか？？

**Comment by nagaihiroki-git** [comment]
> おそらくwiz-uiでコンポーネントを提供しなくとも実装できる内容だと思うので、いったんproduct側で実装してください！ 今後、こういったUIが頻繁に用いられるようでしたら導入を検討いたします！

承知いたしました！

**Comment by ichi-h** [comment]
お願いいたします！:bow:
