### ISSUE TITLE
Bug(WizDatePicker): disabled時の文字色が少し濃い

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#750]
**バグの説明**
WizTimePickerがdisabled時に文字色が薄くなっているのに対し、WizDatePickerは薄くなっていない

**再現手順・画像・動画**
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/43909370/afb2fd12-5bc0-4de1-8e27-3cef6b498a56)

**期待される挙動・機能**
薄くなっている

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
これは #751 と同じだと思います
