### ISSUE TITLE
Bug(WizDatePicker/WizTimePicker): 値が入っている時にdisabled時の文字色が少し濃い

### ISSUE THREAD

**Issue by Maple0922** [Wizleap-Inc/wiz-ui#751]
**バグの説明**
値が入っている時にdisabledにすると、文字色が少し濃い
(仕様であればcloseしてください🙇‍♂️)

**再現手順・画像・動画**
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/43909370/20835696-f410-4c50-88bf-135f5cdb5171)
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/43909370/2b0240eb-a933-48a3-b6f4-13dfd4a9b99c)

**期待される挙動・機能**
薄くなっている

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
Figma では、Font Color は `gray.700` となっているのですが、実際に描写されているのは `gray.500` ですね。
他のコンポーネントに倣って `gray.500` に統一したいと思います。 

![スクリーンショット 2023-05-25 23 40 27](https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/4afe1b1f-48d7-42fd-b007-043da7b5be7b)
