### ISSUE TITLE
Feat: ToggleSwitchに色を追加してユーザーにわかりやすくして欲しい

### ISSUE THREAD

**Issue by YamatoKato** [Wizleap-Inc/wiz-ui#752]
**機能追加理由・詳細**
例えばですが、
ToggleSwitchの入力値が`true`の場合、スイッチを緑で塗りつぶす or UIの枠だけ緑。
`false`なら白で塗りつぶす or  UIの枠だけ黒
といった感じで、スイッチの入力情報をユーザーにわかりやすくさせたいです。
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/b5006849-aec5-429c-b157-b5f1a75a22cd)
