### ISSUE TITLE
Bug(popup): safariにおいて表示位置が少しずれる

### ISSUE THREAD

**Issue by ichi-h** [Wizleap-Inc/wiz-ui#849]
**バグの説明**

https://wizleap.slack.com/archives/C03UB1CL2LS/p1686902913377839

dialog内でselectboxを使いオプションを開いたところ、表示位置がpopup-controllerから少しズレて表示される
オプションが長く、回り込みロジックが発火していた可能性あり

**再現手順・画像・動画**

**期待される挙動・機能**

**その他考慮事項（任意）**

**Comment by okakyo** [comment]
Safari で動作検証してみたが、Selectbox で ずれている様子が確認できなかった。

![スクリーンショット 2023-07-01 16 41 55](https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/1ec439ef-c3c1-4caf-ae4f-ee8aa2e740f9)

**Comment by okakyo** [comment]
調べてみたところ、今回発生したバグのバージョンは v1.11.2, 
回り込みのロジックが解消されたのは [v1.11.3](https://github.com/Wizleap-Inc/wiz-ui/releases/tag/%40wizleap-inc%2Fwiz-ui%401.11.3) ですでに解消済みになっているかもしれない。

バージョンを更新してもらって結果を松

**Comment by okakyo** [comment]
https://wizleap.slack.com/archives/C03UB1CL2LS/p1688201445033469?thread_ts=1686902913.377839&cid=C03UB1CL2LS 

にて解消されたとのこと
