### ISSUE TITLE
Bug: ReactのNavigation実装が標準のアンカータグになっていてSPA遷移できない

### ISSUE THREAD

**Issue by sor4chi** [Wizleap-Inc/wiz-ui#912]
**バグの説明**
![ScreenCapture 2023-07-05 12 39 13](https://github.com/Wizleap-Inc/wiz-ui/assets/80559385/b8f6beea-7071-4dcd-8858-3483f9bafc7a)

**再現手順・画像・動画**
example-vue2かvue3でも同様の現象が起きてますのでそちらを見てください。

**期待される挙動・機能**
`#ffffff`の部分がNavBar幅まで広がるべき

**その他考慮事項（任意）**

**Comment by RyushiAok** [comment]
`WizNavItem`についてですが、次のように使用されることが想定されております。
```vue
<WizNavContainer> 
  <WizNavItem :icon="WizIDashboard" label="Home" to="/" :active="true" />
  <WizNavItem :icon="WizIAssignment" label="Page1" to="/page1" :active="false" />
  <WizNavItem :icon="WizIBusinessCenter" label="Page2" to="/page2" :active="false" />
  <WizNavItem :icon="WizIHelp" label="Page3" to="/page3" :active="false" /> 
</WizNavContainer>
```

該当のexampleを確認したところ、`WizNavContainer`の子が`div`、孫が`WizNavItem`として展開されるため、これが原因で`WizNavItem`が`WizNavContainer`の幅いっぱいに広がらないようでした。

試しに以下のようにStoryを書き換えてみたところ、同様の現象が確認できました。
```vue
<WizNavContainer>
  <div>
    <WizNavItem :icon="WizIDashboard" label="Home" to="/" :active="true" />
    <WizNavItem :icon="WizIAssignment" label="Page1" to="/page1" :active="false" />
    <WizNavItem :icon="WizIBusinessCenter" label="Page2" to="/page2" :active="false" />
    <WizNavItem :icon="WizIHelp" label="Page3" to="/page3" :active="false" />
  </div>
</WizNavContainer>
```
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/55625375/3d51cc72-0a3c-41da-82ca-4dd4a04f2266)

**Comment by sor4chi** [comment]
なるほど、前までこれで動いてたので内部仕様が変わったんですかね？
とりあえずやってみます、ありがとうございます

**Comment by sor4chi** [comment]
かいけつしました

**Comment by sor4chi** [comment]
@RyushiAok 
https://github.com/Wizleap-Inc/money-career-clients/pull/8

こちらのPRで立川さんよりご指摘いただいたのですが、react-routerがwiz-uiに内包されておらず、onClickの遷移しかできない設計になっているため、divでラップしてonClickを当てていたようです。

wiz-uiはvue-routerを内包しており、router-linkによる遷移を行うことでSPA linkを実現しているのですが、wiz-ui-reactのnavigationはaタグの画面遷移になっており、画面のリロードが遷移時に挟まってしまうようです。
こちらに関して、直せそうですか？

**Comment by sor4chi** [comment]
@RyushiAok 
こちら、立川さんが担当してくださるそうです。
