### ISSUE TITLE
Feat: スマホグローバルナビ

### ISSUE THREAD

**Issue by kayokoito-dev** [Wizleap-Inc/wiz-ui#922]
**機能追加理由・詳細**
以下のような動きが理想としています。
※ただし、上のヘッダー部分は、✗→＝になる時に横にMove outしていくことは無く、✗→＝に切り替わるだけなのでご注意ください（Figmaスキルの限界）

https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/dd3cddf8-f741-4544-a9da-26db7f60bfbd

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
- ハンバーガーが出てくるときにもアニメーション
- ヘッダーにもアニメーションがかかっているが、ハンバーガーのところだけアニメーションを効かせる

**Comment by ichi-h** [comment]
いい感じの名前をお願いいたします！

**Comment by RyushiAok** [comment]
WizDrawer
