### ISSUE TITLE
Feat(Stack): [Breaking] 系のコンポーネントでwrap(props)が使いにくいので変えたい

### ISSUE THREAD

**Issue by sor4chi** [Wizleap-Inc/wiz-ui#928]
**機能追加理由・詳細**
現状Stackはwrap=trueがデフォルトのpropsがあり、wrapをオフにするには
```
        <WizHStack gap="md" height="40px" wrap={false}>
```
と書かなければならない
このインターフェースが分かりづらいので変えたい

**解決策の提案（任意）**
nowrap(boolean) = false(default)
にして、wrapを消せば綺麗になりそう

**その他考慮事項（任意）**
一応Breakingとつけたが、wrap={false}は残したままnowrapをつけると、後方互換性を持ったまま修正できる

**Comment by ichi-h** [comment]
- 影響範囲は広いが、やりたい
- 時間取って検討したい

**Comment by ichi-h** [comment]
- 現状
  - wrap: falseがバグによってデフォルト
-  理想
  - nowrap: false
  - wrap: true (deprecated)

vueは一旦スルー、reactだけで対応

**Comment by ichi-h** [comment]
- nowrap: false, wrap: true
  - wrap
- nowrap: true, wrap: false
  - nowrap
- nowrap: true, wrap: true
  - nowrap
- nowrap: false, wrap: false
  - wrap
- nowrap: undefined, wrap: false
  - nowrap
- nowrap: undefined, wrap: true
  - wrap
- nowrap: false, wrap: undefined
  - wrap
- nowrap: true, wrap: undefined
  - nowrap
- nowrap: undefined, wrap: undefined
  - wrap
