### ISSUE TITLE
Feat: (ShowMoreLess)PC用の変更とスマホ用の追加

### ISSUE THREAD

**Issue by kayokoito-dev** [Wizleap-Inc/wiz-ui#934]
**機能追加理由・詳細**

![ShowMoreLess](https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/b417da6c-9333-460a-97eb-05c59e9b1bdb)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
- propsにvariantを追加して制御
  - pc: サイズ小さい方、ホバーしたときに色が変わる
  - mobile: サイズ大きい方、ホバーしても色は変わらない（グレーの方）
