### ISSUE TITLE
Feat: (MenuItem)色の修正

### ISSUE THREAD

**Issue by kayokoito-dev** [Wizleap-Inc/wiz-ui#935]
**機能追加理由・詳細**

![MenuItem](https://github.com/Wizleap-Inc/wiz-ui/assets/67885447/a16774a0-354d-477c-b23b-382af2201dc7)

**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
- css制御
  - 通常時
  - hover
  - active
- js制御 (propsで管理)
  - disable
  - selected
