### ISSUE TITLE
Feat: location cityアイコンを追加していただきたいです！

### ISSUE THREAD

**Issue by nagaihiroki-git** [Wizleap-Inc/wiz-ui#993]
**機能追加理由・詳細**
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:location_city:FILL@0;wght@200;GRAD@0;opsz@48&icon.query=location+city
**解決策の提案（任意）**

**その他考慮事項（任意）**

**Comment by ichi-h** [comment]
#966 と重複なのでcloseします
